development:
  adapter: postgresql
  # encoding: unicode
  database: web_design_project_development
  pool: 5
  host: localhost
  username: web
  password: admin

test:
  adapter: postgresql
  # encoding: unicode
  database: web_design_project_test
  pool: 5
  host: localhost
  username: web
  password: admin

production:
  adapter: postgresql
  # encoding: unicode
  database: rsa_production
  pool: 5
  host: localhost
  username: web
  password: admin
